export type PhaseId = 1 | 2 | 3 | 4;

export type Gate = {
  id: string;
  phase: PhaseId;
  title: string;
  summary: string;
  source: string;
  command: string;
  tag: string;
  optional?: boolean;
  focus?: string;
};

export const phases = [
  {
    id: 1 as const,
    eyebrow: "Phase 01",
    title: "Go foundations",
    shortTitle: "Foundations",
    description: "Ownership, interfaces, errors, semantics, and test craft.",
  },
  {
    id: 2 as const,
    eyebrow: "Phase 02",
    title: "Commerce system",
    shortTitle: "Commerce",
    description: "Build one Order request path through real production boundaries.",
  },
  {
    id: 3 as const,
    eyebrow: "Phase 03",
    title: "llm-d prerequisites",
    shortTitle: "Prerequisites",
    description: "Concurrency, Kubernetes, packaging, mesh, and observability.",
  },
  {
    id: 4 as const,
    eyebrow: "Phase 04",
    title: "llm-d Router",
    shortTitle: "Router",
    description: "Data Layer to scheduling, flow control, proxy, and runtime.",
  },
];

const infrastructureContract = (name: string) =>
  `go test ./test/contracts/infrastructure -run '^${name}$' -count=1`;

export const gates: Gate[] = [
  {
    id: "F0",
    phase: 1,
    title: "Data ownership",
    summary: "Move through slices, maps, UTF-8, and equality without leaking aliases.",
    source: "internal/foundation/language/data_test.go",
    command: "go test ./internal/foundation/language -run '^TestDataFoundations$' -count=1",
    tag: "language",
  },
  {
    id: "F1",
    phase: 1,
    title: "Interface boundaries",
    summary: "Method sets, typed nil, narrow consumer contracts, and streaming inputs.",
    source: "internal/foundation/language/interfaces_test.go",
    command: "go test ./internal/foundation/language -run '^TestInterfaceFoundations$' -count=1",
    tag: "language",
  },
  {
    id: "F2",
    phase: 1,
    title: "Go semantics",
    summary: "Value parts, addressability, defer, panic, scope, and nil behavior.",
    source: "internal/foundation/language/semantics_test.go",
    command: "go test ./internal/foundation/language -run 'Test(ValuePartsAndAddressability|DeferPanicAndScope|NilMapAndChannelSemantics)$' -count=1",
    tag: "language",
  },
  {
    id: "F3",
    phase: 1,
    title: "Error identity",
    summary: "Preserve stable domain meaning through Is, As, Unwrap, and deep wrapping.",
    source: "internal/foundation/language/errors_test.go",
    command: "go test ./internal/foundation/language -run 'TestDomainError_(Is|As|Unwrap|DeepWrapping)$' -count=1",
    tag: "errors",
  },
  {
    id: "F4",
    phase: 1,
    title: "Test craft",
    summary: "Tables, properties, mutation strength, deterministic tests, and fuzzing.",
    source: "internal/foundation/testing/testcraft_test.go",
    command: "go test ./internal/foundation/testing -run '^(Test(SplitSuite_(PassesTheCorrectImplementation|CatchesEveryMutant)|Check(SumsToTotal|NearlyEqual|RemainderGoesFirst)|SplitEvenly_(Examples|Errors))|FuzzSplit)$' -count=1",
    tag: "testing",
  },
  {
    id: "E0",
    phase: 2,
    title: "Commerce values",
    summary: "Protect Money, Quantity, and Address invariants at construction time.",
    source: "internal/commerce/domain/money.go",
    command: "go test ./test/e2e -run '^TestM1_' -count=1",
    tag: "domain",
  },
  {
    id: "E1",
    phase: 2,
    title: "Order aggregate",
    summary: "Own lifecycle transitions, invariants, and immutable domain events.",
    source: "internal/commerce/domain/order.go",
    command: "go test ./test/e2e -run '^TestM2_' -count=1",
    tag: "domain",
  },
  {
    id: "E2",
    phase: 2,
    title: "Application use case",
    summary: "Create an Order through consumer-owned ports and explicit orchestration.",
    source: "internal/commerce/application/order_service.go",
    command: "go test ./test/e2e -run '^TestM3_' -count=1",
    tag: "application",
  },
  {
    id: "E3",
    phase: 2,
    title: "Concurrent persistence",
    summary: "Return defensive snapshots while protecting repository state under load.",
    source: "internal/commerce/persistence/memory_repo.go",
    command: "go test ./test/e2e -run '^TestM4_' -count=1",
    tag: "persistence",
  },
  {
    id: "E4",
    phase: 2,
    title: "Domain events",
    summary: "Publish to every subscriber with explicit goroutine and channel ownership.",
    source: "internal/commerce/eventbus/eventbus.go",
    command: "go test ./test/e2e -run '^TestM5_' -count=1",
    tag: "events",
  },
  {
    id: "E5",
    phase: 2,
    title: "HTTP Order path",
    summary: "Drive the use case through bounded decoding and a real net/http boundary.",
    source: "internal/commerce/http/handler.go",
    command: "go test ./test/e2e -run '^TestM6_' -count=1",
    tag: "http",
  },
  {
    id: "E6",
    phase: 2,
    title: "External error contract",
    summary: "Translate internal failures into stable status codes and response envelopes.",
    source: "test/e2e/milestones_test.go",
    command: "go test ./test/e2e -run '^TestM7_' -count=1",
    tag: "http",
  },
  {
    id: "C0",
    phase: 3,
    title: "Shared state",
    summary: "Use locks deliberately and publish immutable diagnostic snapshots.",
    source: "internal/foundation/concurrency/concurrency_test.go",
    command: "go test ./internal/foundation/concurrency -run 'Test(SafeCounter|Advanced_RWMutexCacheConcurrentAccess)$' -count=1",
    tag: "concurrency",
  },
  {
    id: "C1",
    phase: 3,
    title: "Backpressure",
    summary: "Build semaphores and bounded workers that respect cancellation and hard limits.",
    source: "internal/foundation/concurrency/advanced_test.go",
    command: "go test ./internal/foundation/concurrency -run 'TestAdvanced_(SemaphoreLimitsConcurrency|SemaphoreTryAcquireAndCancel|BoundedWorkerPoolRunsJobsAndPreservesOrder|BoundedWorkerPoolLimitsConcurrency)$' -count=1",
    tag: "concurrency",
  },
  {
    id: "C2",
    phase: 3,
    title: "Atomic state",
    summary: "Practice counters and one-winner CAS without mistaking atomics for policy.",
    source: "internal/foundation/concurrency/advanced_test.go",
    command: "go test ./internal/foundation/concurrency -run 'TestAdvanced_(AtomicCounter|AtomicFlagOnlyOneWinner)$' -count=1",
    tag: "concurrency",
  },
  {
    id: "C3",
    phase: 3,
    title: "Memory visibility",
    summary: "Prove happens-before publication through Once and channel close.",
    source: "internal/foundation/concurrency/memorymodel_test.go",
    command: "go test ./internal/foundation/concurrency -run 'Test(OnceCellPublishesOneValue|ChannelClosePublishesEarlierWrites)$' -count=1",
    tag: "concurrency",
  },
  {
    id: "K0",
    phase: 3,
    title: "KV prefix cache",
    summary: "Build blocks, chained hashes, and collision-safe longest-prefix matching.",
    source: "internal/inference/prefixcache/prefix_test.go",
    command: "go test ./internal/inference/prefixcache -run '^TestPrefixCacheFoundations$' -count=1",
    tag: "inference",
  },
  {
    id: "Y0",
    phase: 3,
    title: "YAML + Kustomize",
    summary: "Render secure, values-driven workloads with explicit runtime ownership.",
    source: "deploy/inference-lab/base/kustomization.yaml",
    command: `kubectl kustomize deploy/inference-lab/overlays/learning && ${infrastructureContract("TestKubernetesBase")}`,
    tag: "kubernetes",
  },
  {
    id: "P0",
    phase: 3,
    title: "Microservice packaging",
    summary: "Package Router and Model roles into reproducible, bounded containers.",
    source: "deploy/inference-lab/compose.yaml",
    command: `docker compose -f deploy/inference-lab/compose.yaml config --quiet && ${infrastructureContract("TestContainerPackaging")}`,
    tag: "containers",
  },
  {
    id: "H0",
    phase: 3,
    title: "Helm release contract",
    summary: "Model values, resources, rollout safety, tests, and operational notes.",
    source: "deploy/inference-lab/chart/Chart.yaml",
    command: `helm lint deploy/inference-lab/chart -f deploy/inference-lab/chart/values-learning.yaml && ${infrastructureContract("TestHelm")}`,
    tag: "helm",
  },
  {
    id: "T0",
    phase: 3,
    title: "Robot acceptance",
    summary: "Express black-box Router behavior without coupling tests to Go internals.",
    source: "test/acceptance/inference/00_smoke.robot",
    command: `robot --dryrun --output NONE --log NONE --report NONE test/acceptance/inference && ${infrastructureContract("TestRobotContracts")}`,
    tag: "acceptance",
  },
  {
    id: "I0",
    phase: 3,
    title: "Istio boundary",
    summary: "Render ingress, strict mTLS, authorization, and sidecar policy.",
    source: "deploy/inference-lab/istio/kustomization.yaml",
    command: `kubectl kustomize deploy/inference-lab/istio && ${infrastructureContract("TestIstio")}`,
    tag: "mesh",
  },
  {
    id: "O0",
    phase: 3,
    title: "Router metrics",
    summary: "Instrument lifecycle and latency with bounded labels and streaming support.",
    source: "internal/inference/observability/metrics_test.go",
    command: "go test ./internal/inference/observability -run 'Test(Metrics|Instrument|UpdateEndpoints)' -count=1",
    tag: "observability",
  },
  {
    id: "O1",
    phase: 3,
    title: "Prometheus Operator",
    summary: "Deploy monitors, Grafana dashboards, and production diagnostics.",
    source: "deploy/inference-lab/observability/operator.yaml",
    command: `kubectl kustomize deploy/inference-lab/observability && ${infrastructureContract("TestOperator")}`,
    tag: "observability",
  },
  {
    id: "O2",
    phase: 3,
    title: "Local observability",
    summary: "Provision reproducible Prometheus and Grafana services for local drills.",
    source: "deploy/inference-lab/observability/compose.yaml",
    command: `docker compose -f deploy/inference-lab/compose.yaml -f deploy/inference-lab/observability/compose.yaml config --quiet && ${infrastructureContract("TestLocalObservability")}`,
    tag: "observability",
  },
  {
    id: "O3",
    phase: 3,
    title: "Alert rules",
    summary: "Create recording, firing, and recovery behavior from bounded metrics.",
    source: "deploy/inference-lab/observability/prometheus/rules.yml",
    command: `promtool check rules deploy/inference-lab/observability/prometheus/rules.yml && ${infrastructureContract("TestPrometheusRules")}`,
    tag: "observability",
  },
  {
    id: "G0",
    phase: 3,
    title: "Gateway inference API",
    summary: "Learn InferencePool and HTTPRoute ownership through rendered resources.",
    source: "deploy/inference-lab/gaie/resources.yaml",
    command: `kubectl kustomize deploy/inference-lab/gaie && ${infrastructureContract("TestGAIE")}`,
    tag: "gateway-api",
  },
  {
    id: "R0",
    phase: 4,
    title: "Data Layer",
    summary: "Own freshness, ordered updates, tombstones, and cancellable state sources.",
    source: "internal/inference/datalayer/store_test.go",
    command: "go test ./internal/inference/datalayer -run 'Test(Store|FileSource|EventSource)' -count=1",
    tag: "router",
  },
  {
    id: "R1",
    phase: 4,
    title: "Scheduling profile",
    summary: "Compose deterministic Filter, Score, and Pick with explainable evidence.",
    source: "internal/inference/routing/scheduler_test.go",
    command: "go test ./internal/inference/routing -run 'Test(DefaultScheduler|Scheduler|MaxScore)' -count=1",
    tag: "router",
  },
  {
    id: "R2",
    phase: 4,
    title: "Flow control",
    summary: "Protect model servers with bounded fairness, TTL, cancellation, and permits.",
    source: "internal/inference/flowcontrol/controller_test.go",
    command: "go test ./internal/inference/flowcontrol -run 'Test(Queue|Controller)' -count=1",
    tag: "router",
  },
  {
    id: "R3",
    phase: 4,
    title: "Versioned config",
    summary: "Validate fully, publish atomically, retain history, and roll back safely.",
    source: "internal/inference/configuration/manager_test.go",
    command: `go test ./internal/inference/configuration -run 'Test(Manager|Publish|Rollback|Concurrent)' -count=1 && ${infrastructureContract("TestRuntimeConfig")}`,
    tag: "router",
  },
  {
    id: "R4",
    phase: 4,
    title: "Request Handler",
    summary: "Parse, derive request state, admit capacity, and unwind partial acquisition.",
    source: "internal/inference/epp/request_handler_test.go",
    command: "go test ./internal/inference/epp -run 'Test(RequestHandler|OpenAI|RoutingHeader)' -count=1",
    tag: "epp",
  },
  {
    id: "R5",
    phase: 4,
    title: "Production Picker",
    summary: "Make one decision from state, scheduling, flow control, and active config.",
    source: "internal/inference/epp/production_picker_test.go",
    command: "go test ./internal/inference/epp -run 'TestProductionPicker' -count=1",
    tag: "epp",
  },
  {
    id: "R6",
    phase: 4,
    title: "Streaming proxy",
    summary: "Forward bounded requests with cancellation, safe headers, and chunk delivery.",
    source: "internal/inference/httpapi/router_test.go",
    command: "go test ./internal/inference/httpapi -run 'Test(Router|Simulator)' -count=1",
    tag: "proxy",
  },
  {
    id: "R7",
    phase: 4,
    title: "Production runtime",
    summary: "Compose real modules and reconcile config-generation capacity ownership.",
    source: "internal/inference/runtime/runtime_test.go",
    command: "go test ./internal/inference/runtime -run 'TestRuntime' -count=1",
    tag: "runtime",
  },
  {
    id: "R8",
    phase: 4,
    title: "Executable harness",
    summary: "Own Router/Model composition, group failure, signals, and graceful drain.",
    source: "cmd/inference-lab/main_test.go",
    command: "go test ./cmd/inference-lab -run 'Test' -count=1",
    tag: "runtime",
  },
];

export const optionalGates: Gate[] = [
  {
    id: "OPT-SYNTAX",
    phase: 1,
    title: "Niche syntax and compiler details",
    summary: "Flags, conversions, compile-fail rules, bounds-check elimination, and unsafe details on demand.",
    source: "internal/foundation/language/optional_syntax_test.go",
    command: "go test -tags=optional ./internal/foundation/language -run '^TestOptionalSyntaxFoundations$'; go test ./internal/foundation/language -run '^TestCompileFailureRules$'; go test ./internal/foundation/performance -run 'Test(BoundsCheckExercises|FieldAndElementPointers|StringViewAndSafeCopy)$'",
    tag: "syntax",
    optional: true,
    focus: "Use compiler evidence for niche rules; do not turn trivia into production cleverness.",
  },
  {
    id: "OPT-CONCURRENCY",
    phase: 1,
    title: "Extended concurrency patterns",
    summary: "Bridge, tee, singleflight, circuit breaker, striped locks, and condition queues.",
    source: "internal/foundation/concurrency/advanced_test.go",
    command: "go test ./internal/foundation/concurrency -run 'Bridge|Tee|AnyDone|ForwardUntilDone|TryMutex|Striped|SingleFlight|CircuitBreaker|CondQueue'",
    tag: "concurrency",
    optional: true,
    focus: "Compare coordination cost, cancellation, and ownership before adopting a pattern.",
  },
  {
    id: "OPT-PERFORMANCE",
    phase: 1,
    title: "Runtime and performance details",
    summary: "Escape analysis, layout, reflection, bounds checks, profiling, and evidence-led optimization.",
    source: "internal/foundation/performance/escape_test.go",
    command: "go test ./internal/foundation/performance",
    tag: "performance",
    optional: true,
    focus: "Optimize from benchmarks and profiles; keep allocation ownership and measurement honest.",
  },
  {
    id: "OPT-FP",
    phase: 1,
    title: "Collections, resilience, patterns, and FP",
    summary: "Practice Result, Option, composition, iterators, retry policy, containers, and Go patterns.",
    source: "internal/foundation/fp/result_test.go",
    command: "go test ./internal/foundation/collection ./internal/foundation/resilience ./internal/foundation/patterns ./internal/foundation/fp/...",
    tag: "functional",
    optional: true,
    focus: "Practice composition, Result and Option while judging when explicit Go is easier to maintain.",
  },
  {
    id: "OPT-WORKFLOW",
    phase: 2,
    title: "Workflow and alternative concurrency models",
    summary: "Explore compensation, Temporal workflows, actors, replay, and alternative ownership models.",
    source: "internal/commerce/workflows/saga.go",
    command: "go test ./internal/commerce/workflows",
    tag: "workflow",
    optional: true,
    focus: "Make compensation, replay, timeout, and delivery semantics explicit before choosing a workflow model.",
  },
  {
    id: "OPT-COMMERCE",
    phase: 2,
    title: "Advanced Commerce extensions",
    summary: "Promotions, pricing, inventory, settlement, event sourcing, and reconciliation under failure.",
    source: "internal/commerce/pricing/promotion_test.go",
    command: "go test ./internal/commerce/pricing ./internal/commerce/operations ./internal/commerce/integrations",
    tag: "commerce+",
    optional: true,
    focus: "Keep policy deterministic and integration reconciliation idempotent under retries and partial failure.",
  },
];

export const allGates = phases.flatMap((phase) => [
  ...gates.filter((gate) => gate.phase === phase.id),
  ...optionalGates.filter((gate) => gate.phase === phase.id),
]);
export const gateById = new Map(allGates.map((gate) => [gate.id, gate]));
