apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: router-replicas.yaml
images:
  - name: inference-lab
    newName: inference-lab
    newTag: learning
